import FWCore.ParameterSet.Config as cms

tagAndProbe = cms.EDAnalyzer('TagAndProbeAnalyzer',
    hadronSrc = cms.InputTag('tauGenJetsSelectorAllHadrons'),
    tauElectronSrc = cms.InputTag('tauGenJetsSelectorElectrons'),
    tauMuonSrc = cms.InputTag('tauGenJetsSelectorMuons'),
    puSrc = cms.InputTag('slimmedAddPileupInfo'),
    tauSrc = cms.InputTag('slimmedTaus'),
    muonSrc = cms.InputTag('slimmedMuons'),
    electronSrc = cms.InputTag('slimmedElectrons'),
    jetSrc = cms.InputTag('slimmedJets'),
    metSrc = cms.InputTag('slimmedMETs'),
    pvSrc = cms.InputTag('offlineSlimmedPrimaryVertices'),
    triggerSrc1 = cms.InputTag("TriggerResults","","HLT"),
    triggerSrc2 = cms.InputTag("TriggerResults","","HLT2"),
    triggerObjectsSrc = cms.InputTag("selectedPatTrigger"),
    stage2TauSrc1 = cms.InputTag("caloStage2Digis","Tau","RECO"),
    stage2TauSrc2 = cms.InputTag("caloStage2Digis","Tau","HLT2"),
    #stage2MuonSrc = cms.InputTag("gmtStage2Digis","Muon","RECO"),
    genSrc = cms.InputTag("prunedGenParticles","","PAT"),
)
